root = "."
tmp_dir = ".bin"
testdata_dir = "testdata"

[build]
  cmd = "go build -o .bin/main.exe ./cmd/api"
  bin = ".bin/main.exe"
  delay = 1000
  exclude_dir = [".git", ".bin", "assets", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
